# Minimal Docker Compose cluster for ElasticSearch and Kibana
# Put this file any folder creating "logs" and "esdata" folders
# to persist the cluster indices and kibana state

version: "3.7"

services:

  workshop-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: workshop-elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks: 
      - esnet
    ulimits:
      memlock:
        soft: -1
        hard: -1

  workshop-kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: workshop-kibana
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks: 
      - esnet
    depends_on:
      - workshop-elasticsearch

  opensky-loader:
    init: true
    build: ./opensky-loader/
    container_name: opensky-loader
    volumes: 
      - ./opensky-loader/config/index.js:/usr/src/app/config.js
    networks: 
      - esnet
    depends_on:
      - workshop-elasticsearch

  opensky-viewer:
    init: true
    build: ./opensky-viewer/
    container_name: opensky-viewer
    ports:
      - 3000:3000
    volumes: 
      - ./opensky-viewer/env:/usr/src/app/backend/.env
    networks: 
      - esnet
    depends_on:
      - workshop-elasticsearch

volumes:
  esdata:
  opensky-loader:
  opensky-viewer:

networks:
  esnet:
